# Generated by Django 4.2.7 on 2024-10-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent_godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.godown')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=255)),
                ('attributes', models.JSONField()),
                ('image_url', models.URLField(max_length=500)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.godown')),
            ],
        ),
    ]
